project:
  name: quickstart-atlassian-bitbucket
  owner: quickstart-eng@amazon.com
  package_lambda: false
  s3_regional_buckets: true
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - eu-west-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  bitbucket:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      BitbucketVersion: "6.6.0"
      DBMasterUserPassword: $[taskcat_genpass_10S]
      ElasticSearchPassword: $[taskcat_genpass_10S]
      BitbucketAdminPassword: "replaced-by-taskcat-override-file"
      AccessCIDR: "10.0.0.0/0"
      DBMultiAZ: "false"
      DBInstanceClass: db.t2.large
      DBIops: 1000
      DBPassword: $[taskcat_genpass_10S]
      KeyPairName: "replaced-by-taskcat-override-file"
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: "quickstart-atlassian-bitbucket/"
      ExportPrefix: $[taskcat_random-string]
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/quickstart-bitbucket-dc-with-vpc.template.yaml
